server:
  port: 8080

spring:
  application:
    name: oauth-server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: manager